---
title: "National 'Legally Free' Rates"
output: 
  flexdashboard::flex_dashboard:
  orientation: columns
vertical_layout: scroll
social: [ "twitter", "facebook", "menu" ]
source_code: embed
theme: flatly
runtime: shiny

---
  
  
```{r setup, include=FALSE, message=FALSE}
# Load packages and initialize data here
library(flexdashboard)
library(rgdal)
library(leaflet)
library(dplyr)
library(magrittr)
library(readr)
library(knitr)
library(shiny)
```


Choose a Year {.sidebar}
-------------------------------------
```{r}
hr()

selectInput("ffy", label = "Top map federal fiscal year: ",
            choices = 2010:2016, selected = 2016)

```

The map at the top-right shows the point-in-time percentage of legally free children in each state in a federal fiscal year (choose above). The maps are based on [AFCARS](https://www.acf.hhs.gov/cb/research-data-technology/reporting-systems/afcars) data obtained from [NDACAN](https://www.ndacan.cornell.edu/). Clicking on a state will display the numerator and denominator data on which the percentages are based. 

```{r}
hr()

selectInput("ffy2", label = "Bottom map federal fiscal year: ",
            choices = 2010:2015, selected = 2015)

```

The map at the bottom-right shows the percentage of children who exit to "legal permanency"" from "legally free" status in each state within 1 year. Data are displayed based on the federal fiscal year (FFY) that a child entered "legally free" status. The maps are calculated using [AFCARS](https://www.acf.hhs.gov/cb/research-data-technology/reporting-systems/afcars) data obtained from [NDACAN](https://www.ndacan.cornell.edu/). Clicking on a state will display the number of entries to legally free status in that state over the selected FFY (choose above).


Prepared by Partners for Our Children

Maps
-------------------------------------
    
### Point-In-Time Rates
    
```{r}
states <- readOGR("StUS_GCS12.shp",
                  layer = "StUS_GCS12", GDAL1_integer64_policy = TRUE, verbose = FALSE)

dat_legally_free <- read.csv("legally_free.csv")

# state specific zipcodes and data
STATE_SHP <- reactive({
  
states@data <- states@data %>%
  inner_join(dat_legally_free, by = c("st_abbrev" = "st")) %>%
  filter(ffy == input$ffy)

STATE_SHP <- states
  
}) # END OF REACTIVE

# color palette
renderLeaflet({
  
pal <- colorBin(palette = "PuBu", domain = STATE_SHP()$per_leg_free_first_day*100, bins = 8)

state_popup <- paste0("<h3><strong>",
                      scales::percent(STATE_SHP()$per_leg_free_first_day),
                      " Legally Free</strong></h3>",
                      "In the <strong>State of ", 
                      STATE_SHP()$atlas_name,
                      "</strong>, ",
                      "on the first day of federal fiscal year <strong>", 
                      STATE_SHP()$ffy, 
                      "</strong>, ",
                      "there were <strong>",
                      prettyNum(STATE_SHP()$total_kids_in_care_first_day, big.mark = ","),
                      "</strong>",
                      " children in foster care. <br><br>According to <a href='https://www.acf.hhs.gov/cb/research-data-technology/reporting-systems/afcars'>AFCARS</a> data, <strong>",
                      prettyNum(STATE_SHP()$legally_free_first_day, big.mark = ","),
                      "</strong> of those children",
                      " were legally free."
                      )
# plot the map
leaflet(data = STATE_SHP()) %>%
  addProviderTiles(providers$Esri.WorldGrayCanvas) %>% 
  addPolygons(fillColor = ~pal(STATE_SHP()$per_leg_free_first_day*100), 
              fillOpacity = 0.7, 
              color = "white",
              opacity = 1,
              #dashArray = '3',
              weight = 2, 
              popup = state_popup) %>%
  addLegend("bottomleft", 
            pal = pal, 
            values = ~STATE_SHP()$per_leg_free_first_day*100,
            title = "% Legally Free",
            opacity = 1)
  
  
})
```
    
### Entries To and Exits From "Legally Free"

```{r}
states <- readOGR("StUS_GCS12.shp",
                  layer = "StUS_GCS12", GDAL1_integer64_policy = TRUE, verbose = FALSE)

dat_legally_free <- read.csv("legally_free.csv")

# state specific zipcodes and data
STATE_SHP2 <- reactive({
  
states@data <- states@data %>%
  inner_join(dat_legally_free, by = c("st_abbrev" = "st")) %>%
  filter(ffy == input$ffy2)

STATE_SHP2 <- states
  
}) # END OF REACTIVE

# color palette
renderLeaflet({
  
pal <- colorBin(palette = "PuBu", domain = STATE_SHP2()$per_exit_one_year*100, bins = 8)

state_popup <- paste0("<h3><strong>",
                      scales::percent(STATE_SHP2()$per_exit_one_year),
                      " Acheiving Permanency within 1 Year</strong></h3>",
                      "In the <strong>State of ", 
                      STATE_SHP2()$atlas_name,
                      "</strong>, ",
                      "over federal fiscal year <strong>", 
                      STATE_SHP2()$ffy, 
                      "</strong>, ",
                      "there were <strong>",
                      prettyNum(STATE_SHP2()$became_legally_free, big.mark = ","),
                      "</strong>",
                      " children who became legally free (i.e. had a TPR against both parents). <br><br>According to <a href='https://www.acf.hhs.gov/cb/research-data-technology/reporting-systems/afcars'>AFCARS</a> data, <strong>",
                      scales::percent(STATE_SHP2()$per_exit_one_year),
                      "</strong> of children who entered legally free status in ",
                      "<strong>", 
                      STATE_SHP2()$ffy, 
                      "</strong> ",
                      " acheived legal permanency within 365 days.")
                      
# plot the map
leaflet(data = STATE_SHP2()) %>%
  addProviderTiles(providers$Esri.WorldGrayCanvas) %>% 
  addPolygons(fillColor = ~pal(STATE_SHP2()$per_exit_one_year*100), 
              fillOpacity = 0.7, 
              color = "white",
              opacity = 1,
              #dashArray = '3',
              weight = 2, 
              popup = state_popup) %>%
  addLegend("bottomleft", 
            pal = pal, 
            values = ~STATE_SHP2()$per_exit_one_year*100,
            title = "% Exiting w/in 1 yr",
            opacity = 1)
  
  
})
```

